# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb7eec8e20d88b0024ee06f9223fa212f0ef71aaae718ea0583113f55663321b3fa362e7d77271a346faf687c48eac73ee69042e86129e988aeeade838144b1

test:
  secret_key_base: 6744676dcb0bdad0d7490e7beec2b23289b13fcaa1d5a48425b1ccc51cca852e512d77485c0ff7924ead6ea43ecb26d0229ddb29d8c198696fb63f66ed931c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
